.\"
.\"  asm51 0.7
.\"  (C) Copyright 2003-2023 Wojtek Kaniewski <wojtekka@toxygen.net>
.\"
.TH ASM51 1 "Nov 30, 2023"

.SH NAZWA
asm51 \- asembler dla mikrokontrolerów rodziny 8051
.SH SKŁADNIA
.B asm51
[
.B \-vnVh
] [
.BI \-f
.IR format
] [
.BI \-o
.IR plik\_wyjściowy
]
.IR plik\_wejściowy
.SH OPIS
.I asm51
jest dwuprzebiegowym asemblerem dla mikrokontrolerów rodziny 8051. Do jego
cech należą:
.nf
- kompatybilność z większością DOS-owych asemblerów,
- obsługa dyrektyw takich jak EQU, ORG, DB, END, itd.
- składnia Intela,
- pliki wyjściowe w formacie binarnym lub Intel HEX.
.fi
.SH DYREKTYWY
.TP
.B etykieta EQU wartość
Definiuje stałą
.TP
.B etykieta DATA wartość
Definiuje adres bajtu w wewnętrznej pamięci danych
.TP
.B etykieta BIT wartość
Definiuje adres bitu w wewnętrznej pamięci danych
.TP
.B ORG offset
Zmienia offset kolejnej instrukcji lub danych
.TP
.B DB bajty, teksty
Wstawia do pamięci programu bajty lub teksty
.TP
.B DW słowa
Wstawia do pamięci programu słowa
.TP
.B DD dwords
Wstawia do pamięci programu podwójne słowa
.TP
.B $MODxx
Dołącz plik
.I MODxx
gdzie xx oznacza model mikroprocesora
.TP
.B $INCLUDE nazwa\_pliku
Dołącz dowolny plik
.TP
.B END
Koniec programu
.SH WYRAŻENIA
Wyrażenia mogą zawierać następujące działania
.B + - / * & | << >>
i mogą być grupowane za pomocą nawiasów. Mogą zawierać etykiety i stałe,
poza dyrektywami typu 
.I ORG
gdzie wartości muszą być znane w pierwszym przebiegu. Szesnastkowe i dwójkowe
wartości wymagają przyrostków
.B h
i
.B b
odpowiednio. Dodatkowo, wyrażenia mogą zawierać następujące funkcje:
.TP
.B $
Offset aktualnej instrukcji
.TP
.B HIGH(wartość)
Bardziej znaczący bajt słowa
.TP
.B LOW(wartość)
Mniej znaczący bajt słowa
.SH OPCJE
.TP
.B \-n
Nie definiuj domyślnych symboli 8051
.TP
.B \-v
Zwiększ gadatliwość
.TP
.B \-h
Wyświetl informacje o pomocy
.TP
.B \-V
Wyświetl wersję
.TP
.B \-o "\ " plik\_wyjściowy
Podaje nazwę pliku wyjściowego. Domyślnie, jeśli
.B asm51
znajdzie rozszerzenie
.B .asm
w nazwie pliku wejściowego, zamienia je na rozszerzenie formatu wyjściowego.
W innym wypadku dodaje je na końcu nazwy pliku wejściowego.
.TP
.B \-f "\ " format\_wyjściowy
Wybiera format pliku wyjściowego. Aktualnie obsługiwane są formaty
.B bin
i
.B hex
(domyślnie wybierany jest
.B hex
).
.SH KODY BŁĘDÓW
.TP
.B 1
Nieprawidłowe parametry
.TP
.B 2
Błąd otwierania pliku wejściowego
.TP
.B 3
Błąd kompilacji
.SH ZNANE BŁĘDY
.BR bison (1)
wyświetla wiele błędów w parserze, ale działa bez problemów.
.SH AUTOR
Wojtek Kaniewski (wojtekka@toxygen.net)

